#pragma once

typedef enum {
  SQUIRT_COMMAND_SQUIRT,
  SQUIRT_COMMAND_CLI,
  SQUIRT_COMMAND_CD,
  SQUIRT_COMMAND_SUCK,
} command_t;

typedef enum {
  ERROR_SUCCESS,
  ERROR_RECV_FAILED_READING_COMMAND,
  ERROR_RECV_FAILED_READING_NAME_LENGTH,
  ERROR_RECV_FAILED_READING_FILENAME,
  ERROR_RECV_FAILED_READING_FILE_LENGTH,
  ERROR_FAILED_TO_CREATE_DESTINATION_FILE,
  ERROR_RECV_FAILED_READING_FILE_DATA,
  ERROR_WRITE_FAILED_WRITING_FILE_DATA,
  ERROR_FAILED_TO_READ_FILE,
  ERROR_SEND_FAILED_WRITING_FILENAME_LENGTH,
  ERROR_SEND_FAILED_WRITING_FILENAME,
  ERROR_SEND_FAILED_WRITING_DATA,
  ERROR_SEND_FAILED_WRITING_SIZE,
  ERROR_CD_FAILED,
  ERROR_PIPE_OPEN_FAILED,
  ERROR_EXEC_FAILED,
} error_t;

static const int BLOCK_SIZE = 8192;
static const int NETWORK_PORT = 6969;
