#pragma once

typedef enum {
  SQUIRT_COMMAND_SQUIRT,
  SQUIRT_COMMAND_SQUIRT_TO_CWD,
  SQUIRT_COMMAND_CLI,
  SQUIRT_COMMAND_CD,
  SQUIRT_COMMAND_SUCK,
  SQUIRT_COMMAND_DIR,
  SQUIRT_COMMAND_CWD,
  SQUIRT_COMMAND_SET_INFO
} command_t;

typedef enum {
  _ERROR_SUCCESS,
  ERROR_RECV_FAILED,
  ERROR_SEND_FAILED,
  ERROR_CREATE_FILE_FAILED,
  ERROR_FILE_WRITE_FAILED,
  ERROR_FILE_READ_FAILED,
  ERROR_CD_FAILED,
  ERROR_FAILED_TO_CREATE_OS_RESOURCE,
  ERROR_EXEC_FAILED,
  ERROR_SUCK_ON_DIR,
} _error_t;

static const int BLOCK_SIZE = 8192;
static const int NETWORK_PORT = 6969;
