#pragma once

typedef enum {
  ERROR_SUCCESS,
  ERROR_RECV_FAILED_READING_NAME_LENGTH,
  ERROR_RECV_FAILED_READING_FILENAME,
  ERROR_RECV_FAILED_READING_FILE_LENGTH,
  ERROR_FAILED_TO_CREATE_DESTINATION_FILE,
  ERROR_RECV_FAILED_READING_FILE_DATA,
  ERROR_WRITE_FAILED_WRITING_FILE_DATA
} error_t;

static const int BLOCK_SIZE = 8192;
static const int NETWORK_PORT = 6969;
